# Generated by Django 4.0.3 on 2022-03-09 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite_books',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
